In [3]:
import pandas as pd

In [4]:
pan = pd.read_csv(r"C:\Users\Leticia\Documents\Letworkspace\pipiline_hopifield\imputs\featuresPAN.tsv", sep="\t")
pan.head

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Leticia\\Documents\\Letworkspace\\pipiline_hopifield\\imputs\\featuresPAN.tsv'

In [ ]:
pan = pd.read_csv(r"C:\Users\Leticia\Documents\Letworkspace\pipiline_hopifield\imputs\featuresPAN.tsv", sep="\t")
pan.columns = pan.columns.str.strip()
pan['gene_id'] = [gene.split(".")[0].strip() for gene in pan['gene_id']]
pan.head(5)


,gene_name,gene_id
0,TNFRSF4,ENSG00000186827
1,TNFRSF18,ENSG00000186891
2,ATAD3B,ENSG00000160072
3,ENSG00000260179.1,ENSG00000260179
4,ENSG00000234396.3,ENSG00000234396


In [ ]:
pan = pan[['gene_id','gene_name']]

In [ ]:
pan.to_csv('featuresPANcorrigido.tsv',header=None, sep="\t", index=False)

In [ ]:
pan.head(5)

,gene_id,gene_name
0,ENSG00000186827,TNFRSF4
1,ENSG00000186891,TNFRSF18
2,ENSG00000160072,ATAD3B
3,ENSG00000260179,ENSG00000260179.1
4,ENSG00000234396,ENSG00000234396.3


In [ ]:
M = pd.read_csv(r"C:\Users\Leticia\Documents\Letworkspace\pipiline_hopifield\imputs\featuresM.tsv\features.tsv", sep="\t", header=None)
M[0] = M[0].str.strip()
M.head(5)


,0,1,2
0,ENSG00000243485,MIR1302-10,Gene Expression
1,ENSG00000237613,FAM138A,Gene Expression
2,ENSG00000186092,OR4F5,Gene Expression
3,ENSG00000238009,RP11-34P13.7,Gene Expression
4,ENSG00000239945,RP11-34P13.8,Gene Expression


In [ ]:


pan.head(5)

,gene_id,gene_name
0,ENSG00000186827,TNFRSF4
1,ENSG00000186891,TNFRSF18
2,ENSG00000160072,ATAD3B
3,ENSG00000260179,ENSG00000260179.1
4,ENSG00000234396,ENSG00000234396.3


In [ ]:
pan_set = set(pan["gene_id"])
m_set = set(M[0])
interseccao = pan_set & m_set
print(len(interseccao))

30836


In [ ]:
math_set = set(M[1])
pan_setGN = set(pan["gene_name"])
inter_pan_math = pan_set & math_set
print(len(inter_pan_math))

0


In [ ]:
list(pan_set)[:5]

['ENSG00000263583',
 'ENSG00000174928',
 'ENSG00000229585',
 'ENSG00000234451',
 'ENSG00000289175']

In [ ]:
fuji = pd.read_csv(r"C:\Users\Leticia\Documents\Letworkspace\pipiline_hopifield\imputs\features.tsv",sep="\t",header=None)
fuji[0] = fuji[0].str.strip().
fuji.head(5)

SyntaxError: invalid syntax (3377409517.py, line 2)

In [ ]:
fuji_set = set(fuji[0])

In [ ]:
inter_pan_fuj =pan_set & fuji_set
print(len(inter_pan_fuj))

36476


In [ ]:
diferenca_pan_fuji = pan_set - fuji_set
print(len(diferenca_pan_fuji))

25065


In [ ]:
diferenca_pan_M = pan_set - m_set
print(len(diferenca_pan_M))

30705


In [ ]:
pan_features = pd.DataFrame(pan_set)
pan_features.head(5)


,0
0,ENSG00000207304
1,ENSG00000267415
2,ENSG00000131779
3,ENSG00000170509
4,ENSG00000267378


In [ ]:
pan_features.to_csv('featuresPANcorrigido.tsv',header=None, sep="\t", index=False)

In [2]:
import numpy as np
dados = np.load(r"C:\Users\Leticia\Downloads\X_mathys_IMPUTADO_rede35.npy") 
print(dados)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [3]:
from scipy import io, sparse

# Converte o array denso para matriz esparsa CSR
matriz_esparsa = sparse.csr_matrix(dados)

# 3. Salva no formato .mtx (Matrix Market)
io.mmwrite(r"C:\Users\Leticia\Downloads\matriz_esparsa.mtx", matriz_esparsa)
